# Generated by Django 5.2.4 on 2025-08-06 04:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField()),
                ('upi_ref_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockchain_status', models.CharField(choices=[('pending', 'Pending'), ('recorded', 'Recorded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('admin_wallet', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
