# Generated by Django 5.2.4 on 2025-08-06 08:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSpending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title of the welfare activity', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the expenditure')),
                ('category', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('food_distribution', 'Food Distribution'), ('shelter', 'Shelter & Housing'), ('disaster_relief', 'Disaster Relief'), ('elderly_care', 'Elderly Care'), ('child_welfare', 'Child Welfare'), ('skill_development', 'Skill Development'), ('sanitation', 'Sanitation & Hygiene'), ('other', 'Other')], default='other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficiaries', models.CharField(help_text='Who benefited from this spending', max_length=255)),
                ('location', models.CharField(help_text='Location where the activity took place', max_length=255)),
                ('spent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockchain_status', models.CharField(choices=[('pending', 'Pending'), ('recorded', 'Recorded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('admin_wallet', models.CharField(blank=True, max_length=42, null=True)),
                ('receipt_reference', models.CharField(blank=True, help_text='Receipt or bill reference number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-spent_date'],
            },
        ),
    ]
