# Generated by Django 5.2.4 on 2025-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationspending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRecordingSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_mode', models.CharField(choices=[('manual', 'Manual (MetaMask Required)'), ('automatic', 'Automatic (Server-Side Signing)')], default='manual', help_text='Choose between manual MetaMask approval or automatic server-side signing', max_length=20)),
                ('credentials_configured', models.BooleanField(default=False, help_text='Whether encrypted wallet credentials are stored')),
                ('last_auto_session', models.DateTimeField(blank=True, help_text='Last time automatic recording was successfully used', null=True)),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Auto-mode session timeout in minutes')),
                ('max_auto_amount', models.DecimalField(decimal_places=2, default=50000.0, help_text='Maximum amount that can be auto-recorded (safety limit)', max_digits=10)),
                ('auto_recording_enabled', models.BooleanField(default=False, help_text='Master switch for automatic recording (additional safety)')),
                ('last_modified_by', models.CharField(blank=True, help_text='Admin user who last modified these settings', max_length=255, null=True)),
                ('security_audit_date', models.DateTimeField(blank=True, help_text='Last security audit date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Recording Settings',
                'verbose_name_plural': 'Auto Recording Settings',
            },
        ),
    ]
