# Generated by Django 5.2.4 on 2025-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_autorecordingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='attempted_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash from auto-recording attempt (even if receipt timed out)', max_length=66, null=True),
        ),
    ]
