# Generated by Django 5.2.4 on 2025-08-08 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationtransaction_attempted_tx_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='Linked user account (if donated while logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='donor_email',
            field=models.EmailField(blank=True, help_text='Email for receipt (if provided)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='donor_phone',
            field=models.CharField(blank=True, help_text='Phone number (if provided)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='receipt_generated',
            field=models.BooleanField(default=False, help_text='Whether receipt has been generated'),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Unique receipt number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='tax_exemption_claimed',
            field=models.BooleanField(default=False, help_text='Whether 80G tax exemption was claimed'),
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number for contact and UPI transactions', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(help_text='Complete address for tax receipt purposes')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number for tax exemption under 80G (optional)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number in format: ABCDE1234F', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for personalized communication', null=True)),
                ('preferred_donation_causes', models.CharField(blank=True, help_text='Comma-separated list of preferred causes (e.g., education, healthcare, disaster relief)', max_length=500)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the donor profile is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Profile',
                'verbose_name_plural': 'Donor Profiles',
            },
        ),
    ]
