# Generated by Django 5.2.4 on 2025-08-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_remove_failed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorecordingsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=0, help_text='Auto-mode session timeout in minutes (0 = no timeout)'),
        ),
    ]
